const SCREEN_WIDTH = 600
const SCREEN_HEIGHT = 600

const
    VIRTUAL_SCREEN_WIDTH = 300,
    VIRTUAL_SCREEN_HEIGHT= 300

const
    GAME_MAX_SPEED = 160,
    GAME_GASOLINA_INICIAL=50,
    GAME_TEMPO_MAXIMO_PARADO=2

export {
    SCREEN_WIDTH,
    SCREEN_HEIGHT,
    VIRTUAL_SCREEN_WIDTH,
    VIRTUAL_SCREEN_HEIGHT,
    GAME_MAX_SPEED,
    GAME_GASOLINA_INICIAL,
    GAME_TEMPO_MAXIMO_PARADO,
}